try {
  
} catch (e) {
  alert("Извините, возникла ошибка: " + e.message);
} finally {
  alert("Пока!");
}

